apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  labels:
    app: go-grpc
spec:
  selector:
    matchLabels:
      app: go-grpc
  template:
    metadata:
      labels:
        app: go-grpc
    spec:
      containers:
      - name: go-grpc-service
        image: 48959548/go-service:latest
        ports:
        - containerPort: 8081

